### ISSUE TITLE
editing-Assets abschaffen

### ISSUE THREAD

**Issue by kostia** [Scrivito/example_app#35]
Seit der iFrame-Einführung, werden die "schweren" UI-Assets von Scrivito nur dann geladen, wenn sie tatsächlich benötigt werden. Seit dem muss der App-Entwickler sich nicht mehr drum kümmern, dass unterschiedliche Assets in unterschiedlichen Situationen geladen werden sollen. In der einfachsten Situation packt der Entwickler alles in die Dateien `application.js` bzw. `application.css`.

Die Example-App teilt die Assets auf. Das ist seit der iFrame-Einführung unnötig und erzeugt nur zusätzliche Komplexität. Zudem verwirrt es de facto die Entwickler.

Die Dateien gehören abgeschafft. Der Code soll in `application.js` bzw. `application.css` liegen.

**Comment by kostia** [comment]
Ich korrigiere mich: Es geht nur um die JS-Assets. Die CSS-Assets sind bereits vereinigt.

**Comment by cedrics** [comment]
The JS Assets also include the `scrivito` assets directly. There is just one manifest file in the example app. 
However, the JS files that enhance / configure the inplace editing are in the folder `editing` and required by `//= require_tree .` in the `application.js`. Do you propose inlining them in the `application.js` or just moving them from the `editing` folder?

**Comment by kostia** [comment]
I propose to inline everything, since it's the simplest way to integrate our assets. In conjunction with https://github.com/Scrivito/example_app/issues/36 you would need to inline only the CB filters.
